server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gjjn?useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: qyff2011
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      max-wait-millis: 10000
      min-idle: 5
      max-idle: 8
      initial-size: 5
      max-total: 100
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 0
        max-wait: -1
        max-idle: 8
        min-idle: 1
    session:
      host: 127.0.0.1
      port: 6379
      database: 1
  jackson:
    time-zone: GMT+8 
      

mybatis:
  mapper-locations: classpath:mappers/*.xml

#打印sql
#logging:
#  level:
#    com.mochen.dao : debug